services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - '/app/node_modules'
      - './backend:/app'
    ports:
      - 5000:5000
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - '/app/node_modules'
      - ./frontend:/app
