name: Test, Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run unit tests
        run: |
          cd backend
          npx jest --forceExit

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push API image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/notes-master:api -f backend/Dockerfile.dev backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/notes-master:api

      - name: Build and push Client image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/notes-master:client -f frontend/Dockerfile.dev frontend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/notes-master:client

      - name: Build and push Nginx image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/notes-master:nginx -f nginx/Dockerfile.dev nginx
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/notes-master:nginx
